name: NASA Project CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    env:
      CI: true # will disable watch mode in test
      MONGO_URL: mongodb://localhost/nasa
    strategy:
      matrix:
        # will create two build jobs which run in parallel
        # and run through all of the steps
        node-version: [14.x, 16.x]
        mongodb-version: ['4.4']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Use Node.js version 16
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          # node-version: '16'
          node-version: ${{ matrix.node-version }}
      - name: Use MongoDB from Github actions
        uses: supercharge/mongodb-github-action@1.9.0
        with:
          mongodb-version: ${{ matrix.mongodb.version }}
      - run: npm install
      - run: npm run build --prefix client
      - run: npm test
